import type { Metadata } from "next";
import { GeistSans, GeistMono } from "geist/font";
import "./globals.css";

// No need to call GeistSans/GeistMono as functions here
// const geistSans = GeistSans({...});
// const geistMono = GeistMono({...});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // Directly use the variable property from the imported font objects
    <html lang="en" className={`${GeistSans.variable} ${GeistMono.variable}`}>
      <body className="bg-anime-bg antialiased">
        {children}
      </body>
    </html>
  );
}
