# Use a minimal Alpine base image
FROM ubuntu:latest

# Install required dependencies
RUN apt-get update && apt-get install -y

# Expose the default Jekyll port
# EXPOSE 4000

# Default command to serve the site
# CMD ["jekyll", "serve", "--host", "0.0.0.0"]
